steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -exc
      - |
        curl -d '{"branchName":"master"}' -X POST -H "Content-type: application/json" \
          -H "Authorization: Bearer $(gcloud config config-helper --format='value(credential.access_token)')" \
          https://cloudbuild.googleapis.com/v1/projects/gcp-10-mins/triggers/63aaba8b-4bb2-47e2-9da7-88683aa2caad:run